services:
  - type: web
    name: orthocare
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DOCTOR_EMAIL
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
